# Generated by Django 4.1 on 2022-08-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_proveedor_proveedordistribuye'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedordistribuye',
            options={'verbose_name_plural': 'Proveedores Distribuyen'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
