# Generated by Django 4.1 on 2022-08-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='imagenprod',
            new_name='imagen',
        ),
    ]
