# Generated by Django 4.1 on 2022-08-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_rename_imagenprod_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='proveedores',
            field=models.ManyToManyField(to='stock.proveedor'),
        ),
        migrations.DeleteModel(
            name='ProveedorDistribuye',
        ),
    ]
