# Generated by Django 4.1 on 2022-09-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_articulo_proveedores_delete_proveedordistribuye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
